=== scrom/Experiments/data/schema/artefact.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Artefact",
  "type": "object",
  "required": ["object", "name", "description", "attributes"],
  "properties": {
    "object": {
      "type": "string",
      "enum": ["artefact"]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "detailedDescription": {
      "type": "string"
    },
    "synonyms": {
      "type": "array",
      "items": { "type": "string" }
    },
    "attributes": {
      "type": "object",
      "properties": {
        "weight": { "type": "number" },
        "carryWeight": { "type": "number" },
        "type": { "type": "string" },
        "subType": { "type": "string" },
        "imageName": { "type": "string" },
        "extendedInventoryDescription": { "type": "string" },
        "price": { "type": "number" },
        "saleUnit": { "type": "number" },
        "attackStrength": { "type": "number" },
        "canDrawOn": { "type": "boolean" },
        "requiresContainer": { "type": "boolean" },
        "requiredContainer": { "type": "boolean" },
        "isPowder": { "type": "boolean" },
        "isLiquid": { "type": "boolean" },
        "canCollect": { "type": "boolean" },
        "holdsLiquid": { "type": "boolean" },
        "isBreakable": { "type": "boolean" },
        "isDamaged": { "type": "boolean" },
        "isBroken": { "type": "boolean" },
        "canOpen": { "type": "boolean" },
        "lockable": { "type": "boolean" },
        "autoLock": { "type": "boolean" },
        "locked": { "type": "boolean" },
        "hidden": { "type": "boolean" },
        "switched": { "type": "boolean" },
        "requiredComponentCount": { "type": "number" },
        "flammable": { "type": "boolean" },
        "isOn": { "type": "boolean" },
        "charges": { "type": "number" },
        "chargeUnit": { "type": "string" },
        "chargesDescription": { "type": "string" },
        "burnRate": { "type": "number" },
        "combinesDescription": { "type": "string" },
        "plural": { "type": "boolean" },
        "affinityModifier": { "type": "number" },
        "isEdible": { "type": "boolean" },
        "nutrition": { "type": "number" },
        "health": { "type": "number" },
        "hideDeliveryDescription": { "type": "boolean" },
        "sound": { "type": "string" },
        "smell": { "type": "string" },
        "taste": { "type": "string" },
        "position": { "type": "string" },
        "unlocks": { "type": "string" },
        "hasLinkedDoor": { "type": "boolean" },
        "combinesWith": {
          "type": "array",
          "items": { "type": "string" }
      },
        "antibodies": {
          "type": "array",
          "items": { "type": "string" }
        },
        "componentOf":{
          "type": "array",
          "items": { "type": "string" }
        },
        "customAction": {
          "type": "array",
          "items": { "type": "string" }
        },
        "defaultAction": { "type": "string" },
        "defaultResult": { "type": "string" }
      }

    },
    "delivers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "template"],
        "properties": {
          "object": { "type": "string" },
          "template": { "type": "string" }
        }
      }
    },
    "linkedexits": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "longname", "direction", "source", "destination"],
        "properties": {
          "object": { "type": "string", "enum": ["exit"] },
          "longname": { "type": "string" },
          "direction": { "type": "string" },
          "source": { "type": "string" },
          "destination": { "type": "string" },
          "hidden": { "type": "boolean" }
        }
      }
    },
    "missions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "file": { "type": "string" }
        },
        "required": ["file"]
      }
    }
  }
}

=== scrom/Experiments/data/facilities.json
{
  "object": "artefact",
  "name": "facilities",
  "description": "facilities team",
  "detailedDescription": "You press your face to the glass and squint.<br>Is there anyone there?",
  "attributes": {
    "type": "scenery",
    "subType": "intangible"
  },
  "synonyms": [
    "team",
    "facilities team"
  ]
}

=== scrom/Experiments/data/artefacts/gesture.json
{
  "object": "artefact",
  "name": "gesture",
  "description": "rude gesture",
  "detailedDescription": "You flap your arms and prance about staring at yourself.",
  "attributes": {
    "type": "scenery",
    "subType": "intangible",
    "customAction": [
      "get",
      "make"
    ],
    "defaultResult": "You press your face to the glass and make childish signs through the window.<br>Nobody seems to notice and you feel a little foolish."
  },
  "synonyms": [
    "v sign",
    "rude sign",
    "rude gesture"
  ]
}

=== scrom/Experiments/data/handwritten-note.json
{
  "object": "artefact",
  "name": "handwritten note",
  "description": "handwritten note",
  "detailedDescription": "It's barely legible and spotted with blood.",
  "attributes": {
    "defaultAction": "read",
    "type": "book",
    "weight": 0.1,
    "affinityModifier": 3,
    "canCollect": true
  },
  "synonyms": [
    "note",
    "letter",
    "letter from jordan",
    "aileen letter",
    "aileens letter"
  ],
  "missions": [
    {
      "file": "mission-readnotefromjordan"
    }
  ]
}

=== scrom/Experiments/data/photo.json
{
  "object": "artefact",
  "name": "photo",
  "description": "photo",
  "detailedDescription": "The photos are all full of people smiling and enjoying themselves.<br>Even from the short time you've been here, you now recognise a few of the faces here.",
  "attributes": {
    "defaultAction": "read",
    "type": "junk",
    "canCollect": false,
    "hidden": true,
    "canDrawOn": true,
    "customAction": [
      "get"
    ],
    "defaultResult": "These are part of Redgate's 'Memory wall'. They're here to look at and enjoy, not to mess with."
  },
  "synonyms": [
    "photo",
    "photograph",
    "faces"
  ]
}

=== scrom/Experiments/data/plate.json
{
  "object": "artefact",
  "name": "plate",
  "description": "plate",
  "detailedDescription": "It's a standard white mass-produced dinner plate",
  "attributes": {
    "extendedInventoryDescription": "There's $inventory on it.",
    "weight": 0.25,
    "carryWeight": 0.2,
    "type": "container",
    "imageName": "dinnerplate.jpg", 
    "canCollect": true,
    "isBreakable": true,
    "affinityModifier": 0
  },
  "synonyms": [
    "white plate"
  ]
}

=== scrom/Experiments/data/artefacts/violet.json
{
  "object": "artefact",
  "name": "Violet",
  "description": "violet",
  "detailedDescription": "She's usually at reception.",
  "attributes": {
    "type": "scenery",
    "subType": "intangible",
    "customAction": [
      "get",
      "check",
      "find",
      "where is",
      "wheres",
      "where",
      "go"
    ],
    "defaultResult": "You'll need to learn to fend for yourself eventually.<br>Try heading <i>East</i> from here."
  },
  "synonyms": [
    "reception",
    "violet",
    "voilet"
  ]
}

=== scrom/Experiments/data/plaque.json
{
  "object": "artefact",
  "name": "plaque",
  "description": "a shiny gold plaque.",
  "detailedDescription": "Somebody has some strange ideas here.<br>It's worth a read for the sheer oddness of the writing in a modern software company.",
  "attributes": {
    "defaultAction": "read",
    "weight": 0,
    "type": "scenery",
    "customAction": [
      "read"
    ],
    "defaultResult": "It says 'Whosoever contributeth most to our billion-dollar revenue is rightwise born to pull out this sword of this stone and table.'",
    "imageName": "plaque.jpg"
  },
  "synonyms": [
    "shiny plaque",
    "shiny gold plaque",
    "gold plaque",
    "brass plaque"
  ]
}

=== scrom/Experiments/data/artefacts/smoke.json
{
  "object": "artefact",
  "name": "smoke",
  "description": "smoke",
  "detailedDescription": "You can't see much although a hint of ash floats by in the breeze.",
  "attributes": {
    "type": "scenery",
    "subType": "intangible",
    "smell": "It's going to linger in your nose and memories for quite some time."
  },
  "synonyms": [
    "ash",
    "wreckage",
    "burning",
    "hint of ash",
    "debris",
    "bodies"
  ]
}
