=== scrom/Experiments/data/schema/artefact.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Artefact",
  "type": "object",
  "required": ["object", "name", "description", "attributes"],
  "properties": {
    "object": {
      "type": "string",
      "enum": ["artefact"]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "detailedDescription": {
      "type": "string"
    },
    "synonyms": {
      "type": "array",
      "items": { "type": "string" }
    },
    "attributes": {
      "type": "object",
      "properties": {
        "weight": { "type": "number" },
        "carryWeight": { "type": "number" },
        "type": { "type": "string" },
        "subType": { "type": "string" },
        "imageName": { "type": "string" },
        "extendedInventoryDescription": { "type": "string" },
        "price": { "type": "number" },
        "saleUnit": { "type": "number" },
        "attackStrength": { "type": "number" },
        "canDrawOn": { "type": "boolean" },
        "requiresContainer": { "type": "boolean" },
        "requiredContainer": { "type": "boolean" },
        "isPowder": { "type": "boolean" },
        "isLiquid": { "type": "boolean" },
        "canCollect": { "type": "boolean" },
        "holdsLiquid": { "type": "boolean" },
        "isBreakable": { "type": "boolean" },
        "isDamaged": { "type": "boolean" },
        "isBroken": { "type": "boolean" },
        "canOpen": { "type": "boolean" },
        "lockable": { "type": "boolean" },
        "autoLock": { "type": "boolean" },
        "locked": { "type": "boolean" },
        "hidden": { "type": "boolean" },
        "switched": { "type": "boolean" },
        "requiredComponentCount": { "type": "number" },
        "flammable": { "type": "boolean" },
        "isOn": { "type": "boolean" },
        "charges": { "type": "number" },
        "chargeUnit": { "type": "string" },
        "chargesDescription": { "type": "string" },
        "burnRate": { "type": "number" },
        "combinesDescription": { "type": "string" },
        "plural": { "type": "boolean" },
        "affinityModifier": { "type": "number" },
        "isEdible": { "type": "boolean" },
        "nutrition": { "type": "number" },
        "health": { "type": "number" },
        "hideDeliveryDescription": { "type": "boolean" },
        "sound": { "type": "string" },
        "smell": { "type": "string" },
        "taste": { "type": "string" },
        "position": { "type": "string" },
        "unlocks": { "type": "string" },
        "hasLinkedDoor": { "type": "boolean" },
        "combinesWith": {
          "type": "array",
          "items": { "type": "string" }
      },
        "antibodies": {
          "type": "array",
          "items": { "type": "string" }
        },
        "componentOf":{
          "type": "array",
          "items": { "type": "string" }
        },
        "customAction": {
          "type": "array",
          "items": { "type": "string" }
        },
        "defaultAction": { "type": "string" },
        "defaultResult": { "type": "string" }
      }

    },
    "delivers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "template"],
        "properties": {
          "object": { "type": "string" },
          "template": { "type": "string" }
        }
      }
    },
    "linkedexits": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "longname", "direction", "source", "destination"],
        "properties": {
          "object": { "type": "string", "enum": ["exit"] },
          "longname": { "type": "string" },
          "direction": { "type": "string" },
          "source": { "type": "string" },
          "destination": { "type": "string" },
          "hidden": { "type": "boolean" }
        }
      }
    },
    "missions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "file": { "type": "string" }
        },
        "required": ["file"]
      }
    }
  }
}

=== scrom/Experiments/data/air.json
{
  "object": "artefact",
  "name": "air",
  "description": "smell of smart people and coffee",
  "detailedDescription": "As I said - smart people and coffee.",
  "attributes": {
    "type": "scenery",
    "subType": "intangible",
    "customAction": [
      "get"
    ],
    "defaultResult": "The place is full of 'em. Go explore!",
    "smell": "You detect the slightly warm, damp, youthful smell of Cambridge graduates."
  },
  "synonyms": [
    "smart",
    "smart people",
    "people",
    "graduates"
  ]
}

=== scrom/Experiments/data/whiteboard-pen.json
{
"object": "artefact",
"name": "pen",
"description": "whiteboard pen",
"detailedDescription": "It's a black pen.",
"attributes": {
    "weight": 0.2,
    "type": "writing",
    "canCollect": true,
    "charges": 20,
    "chargeUnit": "use",
    "chargesDescription": "It's good for about $charges more $chargeUnit"
},
"synonyms": [
	"black pen",
    "board pen",
    "whiteboard pen"
]
}

=== scrom/Experiments/data/artefacts/fez.json
{
  "object": "artefact",
  "name": "fez",
  "description": "red fez",
  "detailedDescription": "Is it socially acceptable to wear one of these?",
  "attributes": {
    "weight": 4,
    "type": "junk",
    "canCollect": true,
    "position": "on",
    "imageName": "camelids.jpg",
    "customAction": [
      "wear"
    ],
    "defaultResult": "The tommy cooper look doesn't suit you."
  },
  "synonyms": [
    "red",
    "red fez",
    "hat",
    "red hat"
  ]
}

=== scrom/Experiments/data/artefacts/batteries.json
{
"object": "artefact",
"name": "batteries",
"description": "torch batteries",
"detailedDescription": "They're pretty chunky but fairly old-looking.",
"attributes": {
    "weight": 1,
    "canCollect": true,
    "imageName": "batteries.jpg", 
    "charges": 45,
    "chargeUnit": "minute",
    "chargesDescription": "There's enough for about $charges $chargeUnit of power",
    "plural": true,
    "affinityModifier": 0,
    "componentOf": [
    "torch"
    ]
},
"synonyms": [
    "battery",
    "torch batteries"
]
}

=== scrom/Experiments/data/artefacts/security-article.json
{
  "object": "artefact",
  "name": "article on software security",
  "description": "'Learn on the Loo' article",
  "detailedDescription": "It's entitled 'Take security in your STRIDE'.",
  "attributes": {
    "defaultAction": "read",
    "weight": 3,
    "attackStrength": 5,
    "type": "book",
    "canCollect": true,
    "canDrawOn": true
  },
  "synonyms": [
    "security article",
    "article",
    "lotl",
    "learn on the loo",
    "learn on the loo article",
    "loo article",
    "learn article"
  ],
  "missions": [
    {"file": "mission-lotlsecurity"}
  ]
}

=== scrom/Experiments/data/indoor-plant.json
{
"object": "artefact",
"name": "plant",
"description": "potted office plant",
"detailedDescription": "It's an ornamental evergreen variety (like most of the pants in the building).<br>This one's a generic yucca/palm/cactus type thing (nothing particularly interesting).",
"attributes": {
    "weight": 3,
    "type": "scenery",
    "imageName": "plant.jpg",
    "subType": "plant",
    "position": "on",
    "combinesWith": [
    "water"
    ]
},
"synonyms": [
    "potted plant"
]
}

=== scrom/Experiments/data/artefacts/wall-servery-north-west.json
{
  "object": "artefact",
  "name": "wall",
  "description": "wall full of post cards and photos",
  "detailedDescription": "You poke through the postcards interspersed with the photos. They generally have variations of 'thanks', 'you're wonderful' and similar meaningful platitudes.<br><br>You're tempted to take one of these to <i>give</i> to someone.",
  "attributes": {
    "weight": 280,
    "type": "scenery",
    "canDrawOn": true,
    "customAction": [
      "get"
    ],
    "defaultResult": "Taking just the one postcard was enough."
  },
  "synonyms": [
    "cards",
    "photo",
    "photos",
    "postcards",
    "postcard",
    "post cards",
    "card wall",
    "walls"
  ]
}

=== scrom/Experiments/data/artefacts/sign.json
{
  "object": "artefact",
  "name": "sign",
  "description": "out of order sign",
  "detailedDescription": "It says 'Temporarily out of order'.",
  "attributes": {
    "weight": 0,
    "position": "on",
    "type": "scenery",
    "canDrawOn": true,
    "customAction": [
      "read"
    ],
    "defaultResult": "It says: 'Due to a series of blockages and poor plumbing, this cubicle is currently out of order'."
  },
  "synonyms": [
    "tatty sign"
  ]
}
