=== scrom/Experiments/data/schema/artefact.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Artefact",
  "type": "object",
  "required": ["object", "name", "description", "attributes"],
  "properties": {
    "object": {
      "type": "string",
      "enum": ["artefact"]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "detailedDescription": {
      "type": "string"
    },
    "synonyms": {
      "type": "array",
      "items": { "type": "string" }
    },
    "attributes": {
      "type": "object",
      "properties": {
        "weight": { "type": "number" },
        "carryWeight": { "type": "number" },
        "type": { "type": "string" },
        "subType": { "type": "string" },
        "imageName": { "type": "string" },
        "extendedInventoryDescription": { "type": "string" },
        "price": { "type": "number" },
        "saleUnit": { "type": "number" },
        "attackStrength": { "type": "number" },
        "canDrawOn": { "type": "boolean" },
        "requiresContainer": { "type": "boolean" },
        "requiredContainer": { "type": "boolean" },
        "isPowder": { "type": "boolean" },
        "isLiquid": { "type": "boolean" },
        "canCollect": { "type": "boolean" },
        "holdsLiquid": { "type": "boolean" },
        "isBreakable": { "type": "boolean" },
        "isDamaged": { "type": "boolean" },
        "isBroken": { "type": "boolean" },
        "canOpen": { "type": "boolean" },
        "lockable": { "type": "boolean" },
        "autoLock": { "type": "boolean" },
        "locked": { "type": "boolean" },
        "hidden": { "type": "boolean" },
        "switched": { "type": "boolean" },
        "requiredComponentCount": { "type": "number" },
        "flammable": { "type": "boolean" },
        "isOn": { "type": "boolean" },
        "charges": { "type": "number" },
        "chargeUnit": { "type": "string" },
        "chargesDescription": { "type": "string" },
        "burnRate": { "type": "number" },
        "combinesDescription": { "type": "string" },
        "plural": { "type": "boolean" },
        "affinityModifier": { "type": "number" },
        "isEdible": { "type": "boolean" },
        "nutrition": { "type": "number" },
        "health": { "type": "number" },
        "hideDeliveryDescription": { "type": "boolean" },
        "sound": { "type": "string" },
        "smell": { "type": "string" },
        "taste": { "type": "string" },
        "position": { "type": "string" },
        "unlocks": { "type": "string" },
        "hasLinkedDoor": { "type": "boolean" },
        "combinesWith": {
          "type": "array",
          "items": { "type": "string" }
      },
        "antibodies": {
          "type": "array",
          "items": { "type": "string" }
        },
        "componentOf":{
          "type": "array",
          "items": { "type": "string" }
        },
        "customAction": {
          "type": "array",
          "items": { "type": "string" }
        },
        "defaultAction": { "type": "string" },
        "defaultResult": { "type": "string" }
      }

    },
    "delivers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "template"],
        "properties": {
          "object": { "type": "string" },
          "template": { "type": "string" }
        }
      }
    },
    "linkedexits": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["object", "longname", "direction", "source", "destination"],
        "properties": {
          "object": { "type": "string", "enum": ["exit"] },
          "longname": { "type": "string" },
          "direction": { "type": "string" },
          "source": { "type": "string" },
          "destination": { "type": "string" },
          "hidden": { "type": "boolean" }
        }
      }
    },
    "missions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "file": { "type": "string" }
        },
        "required": ["file"]
      }
    }
  }
}

=== scrom/Experiments/data/newspaper.json
{
  "object": "artefact",
  "name": "guardian newspaper",
  "description": "copy of today's Guardian newspaper",
  "detailedDescription": "Middle class pulp propaganda trash.",
  "attributes": {
    "defaultAction": "read",
    "weight": 1,
    "attackStrength": 2,
    "type": "book",
    "imageName": "newspaper.jpg",
    "canCollect": true,
    "defaultResult": "Blah blah government... blah scandal blah crucial blah liberal blah economics etc.",
    "canDrawOn": true
  },
  "synonyms": [
    "guardian",
    "newspaper",
    "news",
    "paper"
  ]
}

=== scrom/Experiments/data/dart.json
{
  "object": "artefact",
  "name": "dart",
  "description": "nerf darts",
  "detailedDescription": "Ping, squeee, ouch, grrr.",
  "attributes": {
    "weight": 0.5,
    "canCollect": true,
    "charges": 10,
    "chargeUnit": "round",
    "chargesDescription": "There's $charges $chargeUnit left",
    "plural": true,
    "affinityModifier": 0,
    "componentOf": [
      "nerf gun"
    ]
  },
  "synonyms": [
    "nerf darts",
    "darts"
  ]
}

=== scrom/Experiments/data/paper.json
{
  "object": "artefact",
  "name": "paper",
  "description": "a3 paper",
  "detailedDescription": "Ahhh, the dream of the paperless office.<br>Maybe one day.",
  "attributes": {
    "weight": 5,
    "attackStrength": 1,
    "canCollect": true,
    "charges": 50,
    "chargeUnit": "sheet",
    "chargesDescription": "There's about $charges $chargeUnit here.",
    "plural": true,
    "affinityModifier": 0,
    "componentOf": [
      "printer"
    ]
  },
  "synonyms": [
    "a3 paper",
    "sheet"
  ]
}

=== scrom/Experiments/data/first-aid-kit.json
{
"object": "artefact",
"name": "first aid kit",
"description": "first aid kit",
"detailedDescription": "There's enough equipment in here to heal a few nasty wounds.",
"attributes": {
    "defaultAction": "heal",
    "weight": 1,
    "type": "medical",
    "imageName": "firstaidkit.jpg", 
    "canCollect": true,
    "isBreakable": true,
    "charges": 5,
    "canDrawOn": true
},
"synonyms": [
    "first aid",
    "kit",
    "firstaid kit",
    "first-aid kit",
    "first-aid"
]
}

=== scrom/Experiments/data/artefacts/visitors-book.json
{
    "object": "artefact",
    "name": "visitors book",
    "description": "visitor's book",
    "detailedDescription": "It looks like you're the first newcomer today.",
    "attributes": {
        "weight": 1,
        "position": "on",
        "imageName": "visitorsbook.jpg",
        "customAction": [
            "get"
        ],
        "defaultResult": "It needs to stay down here on reception.",
        "canDrawOn": true
    },
    "synonyms": [
        "book",
        "visitor book",
        "in"
    ]
}

=== scrom/Experiments/data/strings.json
{
  "object": "artefact",
  "name": "strings",
  "description": "guitar strings",
  "detailedDescription": "They're tatty but functional nylon/wound spanish guitar strings.",
  "attributes": {
    "type": "scenery",
    "weight": 0,
    "canCollect": false,
    "isBreakable": true,
    "plural": true,
    "affinityModifier": 0,
    "componentOf": [
      "guitar"
    ],
    "customAction": [
      "get"
    ],
    "defaultResult": "They look pretty worn out. They'll be no use as a garotte or tourniquet. Their only function is for making plinky sounds on a guitar so it's best to leave them alone."
  },
  "synonyms": [
    "guitar strings",
    "nylon strings",
    "nylon wound strings",
    "nylon-wound strings",
    "nylon guitar strings",
    "spanish guitar strings"
  ]
}

=== scrom/Experiments/data/chairs.json
{
"object": "artefact",
"name": "chairs",
"description": "set of office chairs",
"detailedDescription": "They're just standard office chairs.",
"attributes": {
    "defaultAction": "rest",
    "weight": 30,
    "type": "bed",
    "imageName": "officechairs.jpg", 
    "isBreakable": true,
    "plural": true,
    "customAction": [
    "get"
    ],
    "defaultResult": "It's best to leave them here."
},
"synonyms": [
  "chair",
  "office chair",
  "standard office chair"
]
}

=== scrom/Experiments/data/bike-ambulance-bike-ambulance.json
{
  "object": "artefact",
  "name": "bike ambulance",
  "description": "bike ambulance",
  "detailedDescription": "It's an old converted NHS ambulance. It's pretty beaten-up but looks functional.",
  "attributes": {
    "weight": 3500,
    "type": "scenery",
    "canDrawOn": true
  },
  "synonyms": [
    "ambulance"
  ]
}
